# Generated by Django 5.0.1 on 2024-06-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("password", models.CharField(default="", max_length=256)),
            ],
        ),
    ]
