# Generated by Django 5.0.1 on 2024-06-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "email",
                    models.CharField(
                        default="", max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=16)),
                ("password", models.CharField(default="", max_length=256)),
                ("standard", models.IntegerField(default=0, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Student_Teacher_Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "email",
                    models.CharField(
                        default="", max_length=16, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=16)),
                ("password", models.CharField(default="", max_length=256)),
                ("subject", models.CharField(default="", max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="student_teacher_relation",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.teacher"
            ),
        ),
    ]
