# Generated by Django 5.0.1 on 2024-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_student_student_teacher_relation_teacher_delete_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(
                default="", max_length=32, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.CharField(
                default="", max_length=32, primary_key=True, serialize=False
            ),
        ),
    ]
