# Generated by Django 5.0.1 on 2024-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_student_email_alter_teacher_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="standard",
            field=models.IntegerField(default=0),
        ),
    ]
